production: &default
  client_categories:
    no_cat:
      icon: 'star-empty'
      order: 99
    green_star:
      icon: 'star-green'
      order: 1
    yellow_star:
      icon: 'star-yellow'
      order: 2
    red_star:
      icon: 'star-red'
      order: 3
  like_text:
    - Great!
    - I appreciate it.
    - Good for you!
    - Congratulations!
    - Keep up the hard work.
    - Keep it up!
    - I'm proud of you.
    - Thanks for responding

development:
  <<: *default

staging:
  <<: *default

test:
  client_categories:
    no_cat:
      icon: 'iconX'
      order: 99
    cat1:
      icon: 'icon1'
      order: 1
    cat2:
      icon: 'icon2'
      order: 2
    cat3:
      icon: 'icon3'
      order: 3
  like_text:
    - option1
    - option2
    - option3
    - option4
    - option5
    - option6
    - option7
    - option8
